apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-c2xo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-c2xo
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-c2xo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-c2xo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-c2xo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-amgj-tenant/status-quarkus-io/statusquarkusio-c2xo@sha256:99091673f7a866ef8291302a9b10dead8f6229528812d6bd67c4d442164c47db
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
